lib: [
  "_build/install/default/lib/ppx_heml/META"
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/.public_cmi/ppx_heml.cmi" {"__private__/ppx_heml/.public_cmi/ppx_heml.cmi"}
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/.public_cmi/ppx_heml.cmt" {"__private__/ppx_heml/.public_cmi/ppx_heml.cmt"}
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/ppx_heml.a" {"__private__/ppx_heml/ppx_heml.a"}
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/ppx_heml.cma" {"__private__/ppx_heml/ppx_heml.cma"}
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/ppx_heml.cmx" {"__private__/ppx_heml/ppx_heml.cmx"}
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/ppx_heml.cmxa" {"__private__/ppx_heml/ppx_heml.cmxa"}
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/ppx_heml.ml" {"__private__/ppx_heml/ppx_heml.ml"}
  "_build/install/default/lib/ppx_heml/dune-package"
  "_build/install/default/lib/ppx_heml/opam"
]
libexec: [
  "_build/install/default/lib/ppx_heml/__private__/ppx_heml/ppx_heml.cmxs" {"__private__/ppx_heml/ppx_heml.cmxs"}
]
